# @via https://github.com/docker-library/php/blob/master/7.4/alpine3.12/fpm/Dockerfile
FROM php:7.4.7-fpm-alpine3.12

# @PHP-extensions:
# - imagick
# - pdo_mysql
# - phalcon
# - psr
# - redis
# - swoole
